//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurseryDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NurseryEntities : DbContext
    {
        public NurseryEntities()
            : base("name=NurseryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nursery> Nurseries { get; set; }
        public virtual DbSet<daily_report> daily_report { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<KidImage> KidImages { get; set; }
        public virtual DbSet<Kid> Kids { get; set; }
        public virtual DbSet<SkillHubUser> SkillHubUsers { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
